<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(ModDeployRoot)/ArtsXSkills</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VintageStoryPath)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VintageStoryPath)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VintageStoryPath)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VintageStoryPath)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VintageStoryPath)/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStoryPath)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VintageStoryPath)/Lib/protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(VintageStoryPath)/Lib/cairo-sharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>$(VintageStoryPath)/Lib/Microsoft.Data.Sqlite.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="xlib">
      <HintPath>$(SolutionDir)/dev/dependencies/xlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="xskills">
      <HintPath>$(SolutionDir)/dev/dependencies/xskills.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
  <Content Include="assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>


<ItemGroup>
  <Folder Include="assets\artsxskills\lang\" />
</ItemGroup>


<ItemGroup>
  <Compile Update="Properties\Resources.Designer.cs">
    <DesignTime>True</DesignTime>
    <AutoGen>True</AutoGen>
    <DependentUpon>Resources.resx</DependentUpon>
  </Compile>
</ItemGroup>


<ItemGroup>
  <EmbeddedResource Update="Properties\Resources.resx">
    <Generator>ResXFileCodeGenerator</Generator>
    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
  </EmbeddedResource>
</ItemGroup>

</Project>
