<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(ModDeployRoot)/AOGBreedingAddon</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VintageStoryPath)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VintageStoryPath)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VintageStoryPath)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VintageStoryPath)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VintageStoryPath)/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStoryPath)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VintageStoryPath)/Lib/protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(VintageStoryPath)/Lib/cairo-sharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>$(VintageStoryPath)/Lib/Microsoft.Data.Sqlite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
  <Content Include="assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

</Project>
